### PR TITLE
Postconditions check if value is `Err` before calling `unwrap`

### LINKED ISSUE #23: BUG: Specs sometimes call `unwrap` on assumed valid value in postcondtion
We are seeing many branches in the proof output are failing due to a call to `unwrap_failed`. At least some of these are created because the specs contain bugs where they are calling `unwrap` on a symbolic result type, but they should be branching into a Solana error prior to this `unwrap` if the result is an error.

Consider the example of `test_process_freeze_account` with current proof visualiser tree of:
```
$ python3 scripts/visualize_proof_tree.py artefacts/proof/test_process_freeze_account-full.txt 
🌲 PROOF TREE STRUCTURE
════════════════════════════════════════════════════════════════════════════════
Format: Node ID | Type | Attributes | Line Number
────────────────────────────────────────────────────────────────────────────────

┌─ 1  🌳 ROOT      ((root, init))            │ line     2
├─ 3     NORMAL                              │ line   691
├─ 4  🔀 SPLIT     ((split))                 │ line  5710
┃  ├─ 5     NORMAL                           │ line 10741
┃  ├─ 7     NORMAL                           │ line 15769
┃  ├─ 9     NORMAL                           │ line 20799
┃  ├─ 10 🔀 SPLIT     ((split))              │ line 26115
┃  ┃  ├─ 11    NORMAL                        │ line 31137
┃  ┃  ├─ 13 🔀 SPLIT     ((split))           │ line 36156
┃  ┃  ┃  ├─ 15    NORMAL                     │ line 41186
┃  ┃  ┃  ├─ 19    NORMAL                     │ line 46213
┃  ┃  ┃  └─ 23 ❌ STUCK     ((stuck, leaf))  │ line 51235
┃  ┃  ├─ 16    NORMAL                        │ line 56272
┃  ┃  └─ 20 ❌ STUCK     ((stuck, leaf))     │ line 61299
┃  ├─ 12    NORMAL                           │ line 66337
┃  ├─ 14 🔀 SPLIT     ((split))              │ line 71356
┃  ┃  ├─ 17    NORMAL                        │ line 76386
┃  ┃  ├─ 21    NORMAL                        │ line 81413
┃  ┃  └─ 24 ❌ STUCK     ((stuck, leaf))     │ line 86435
┃  ├─ 18    NORMAL                           │ line 91472
┃  └─ 22 ❌ STUCK     ((stuck, leaf))        │ line 96499
├─ 6     NORMAL                              │ line 101537
└─ 8  ❌ STUCK     ((stuck, leaf))           │ line 106565
┌─ 2  🌳 ROOT      ((root, leaf, target, terminal)) │ line 111623

📊 STATISTICS
════════════════════════════════════════
📈 Total nodes: 24

  ⚪ Normal      :  13
  🌳 Root        :   2
  🔀 Split       :   4
  ❌ Stuck       :   5

🎯 Proof Outcome:
  ❌ STUCK: 5 branch(es) got stuck
```

4 / 5 of the stuck nodes in this branch are failing due to the above problem. Focusing on 1, it can be seen in this [branch of the postcondition](https://github.com/runtimeverification/solana-token/blob/4fbb5119da4c9bbdaeecc3c82761b6163b4a0509/p-token/src/entrypoint-runtime-verification.rs#L2456C15-L2456C41) which ought to have a branch prior that checks of the result is an error. This is because the implementation will call [load_mut](https://github.com/runtimeverification/solana-token/blob/4fbb5119da4c9bbdaeecc3c82761b6163b4a0509/p-token/src/processor/shared/toggle_account_state.rs#L19) that will check if the loaded `T` [is initialised](https://github.com/runtimeverification/solana-token/blob/4fbb5119da4c9bbdaeecc3c82761b6163b4a0509/p-interface/src/state/mod.rs#L74) (which calls [Account::is_initialized](https://github.com/runtimeverification/solana-token/blob/4fbb5119da4c9bbdaeecc3c82761b6163b4a0509/p-interface/src/state/account.rs#L160-L162) in this example), [propagating an ProgramError::InvalidAccountData](https://github.com/runtimeverification/solana-token/blob/4fbb5119da4c9bbdaeecc3c82761b6163b4a0509/p-interface/src/state/account_state.rs#L27) error in the case the state is not valid.

The full proof tree for analysis is available here:
[test_process_freeze_account-full.txt](https://github.com/user-attachments/files/22506028/test_process_freeze_account-full.txt)

The solution is to add the extra branches and that should get us to the `assert_eq` statements ensuring that the error codes are as predicted.

### PR DESCRIPTION
**Pull request by dkcumming**
Previously I had missed checks that `Result` types were not `Err` before calling unwrap, now there are explicit branches and appropriate error codes that reflect P-Token's behaviour in this case. I have not been able to test this concretely with the tests, we are going to have to roll with the proofs.

I also fixed:
- Outdated commands in the documentation for running the proofs
- A copy paste bug in `TransferChecked`

I intend to run the proofs overnight and update the documents that store the info in the morning

Closes https://github.com/runtimeverification/solana-token/issues/23

### CODE REVIEW

File: p-token/src/entrypoint-runtime-verification.rs [hunk 1]
```diff
@@ -2773,13 +2847,16 @@ fn test_process_mint_to_checked(accounts: &[AccountInfo; 3], instruction_data: &
     } else if accounts.len() < 3 {
         assert_eq!(result, Err(ProgramError::NotEnoughAccountKeys));
         return result;
-    } else if accounts[1].data_len() != Account::LEN {
+    } else if accounts[1].data_len() != Account::LEN { // TODO Daniel: is it possible for something to be provided that has the same len but is not an account?
```
Comment (jberthold) [inline p-token/src/entrypoint-runtime-verification.rs:2850]: The cheat codes currently assert that `data_len` is correct for the respective type of thing.
Account: 165, Mint: 82, Rent: 17

**Review by jberthold — APPROVED** [review]
All changes LGTM
